# Generated by Django 5.2 on 2026-01-30 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('unidad_base', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='creado_en',
            new_name='creado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_cliente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='SIRENITA.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('porciones', models.PositiveIntegerField(default=1)),
                ('tiempo_preparacion', models.PositiveIntegerField(default=0, help_text='Minutos')),
                ('tiempo_coccion', models.PositiveIntegerField(default=0, help_text='Minutos')),
                ('dificultad', models.CharField(choices=[('Fácil', 'Fácil'), ('Media', 'Media'), ('Difícil', 'Difícil')], default='Fácil', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='SIRENITA.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PasoPreparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paso', models.PositiveIntegerField()),
                ('descripcion', models.TextField()),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, null=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='SIRENITA.receta')),
            ],
            options={
                'ordering': ['numero_paso'],
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutricion', to='SIRENITA.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recetas/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='SIRENITA.receta')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='SIRENITA.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_detalle', to='SIRENITA.receta')),
            ],
            options={
                'unique_together': {('receta', 'ingrediente')},
            },
        ),
    ]
