# Generated by Django 5.2 on 2026-01-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0003_registropedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='solicitado',
            field=models.BooleanField(default=False),
        ),
    ]
