# Generated by Django 6.0.3 on 2026-03-31 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0005_cupon_pedido_descuento_aplicado_pedido_estado_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('STRIPE', 'Stripe'), ('MERCADOPAGO', 'MercadoPago')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_acceso', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('INTENTO_FALLIDO', 'Intento Fallido')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('navegador', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Acceso',
                'verbose_name_plural': 'Registros de Acceso',
                'db_table': 'tbl_registro_accesos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
