# Generated by Django 6.0.3 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0006_alter_pedido_metodo_pago_registroacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='personas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
