# Generated by Django 6.0.3 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0007_pedido_mesa_personas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'SIRENITA_mesas',
                'ordering': ['mesa'],
            },
        ),
    ]
