# Generated by Django 6.0.3 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIRENITA', '0008_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
